config/routes.rb
Ayosi::Application.routes.draw do
  get "memberships/destroy"
  root to: 'home#index'
  devise_for :users, controllers: { registrations: "registrations"}
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"
  resources :patients, only: [:index, :new, :create, :show]
  resources :users
  resources :data
  resources :designations do
    collection do
      put :make_default
    end
  end
  resources :hospitals do
    resources :users, only: :index
  end
  resources :teams
  resources :memberships, only: :destroy do
    member do
      post :requesting
      post :activating
      post :rejecting
      post :deactivating
      post :banning
      post :resigning
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Designation is the join table for users and hospitals
  has_many :designations, dependent: :destroy
  has_many :hospitals, -> {distinct}, through: :designations

  # Client is the join table for users and patients
  has_many :clients, dependent: :destroy
  has_many :patients, -> {distinct}, through: :clients

  # Membership is the join table for users(members) and teams
  has_many :memberships, dependent: :destroy
  # This will give a collection, eg: member.teams or user.teams, number of teams
  # that she is a member of.
  has_many :teams, -> {distinct}, through: :memberships

  # This defines the ownership of the team and will return a single team, eg:
  # user.team, the team that the user owns. The reverse is defined as a belongs_to
  # in the Team model
  has_one :team, dependent: :destroy

  # Validation for the rest are provided by devise. Validation that follows here are
  # for the extra fields that have been added to the user model eg: name
  validates_presence_of :name
  validates_presence_of :encrypted_password

  accepts_nested_attributes_for :designations
  accepts_nested_attributes_for :clients
  accepts_nested_attributes_for :memberships


  def self.hospital_staff
    where(category: "hospital_staff")
  end

  def self.doctors
    Role.find_by(name: "doctor").users
  end
  
  # These methods will be called upon to associate the hospital automatically with the
  # patient's hospital
  def default_designation
    designations.find_by(is_default: true)
  end

  def default_hospital
    default_designation.hospital unless default_designation.nil?
  end


end

app/controllers/api/v1/users.rb
module API
  module V1
    class Users < Grape::API
      include API::V1::Defaults

      resource :users do
        desc "Return all the users"
        get "", root: :users do
          User.all
        end

        desc "Return a user"
        params do
          requires :id, type: String, desc: "ID of the user"
        end
        get ":id", root: "user" do
          User.where(id: permitted_params[:id].first!)
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user
  respond_to :html

  def show
    @designations = @user.designations
    @teams = @user.teams
  end

  def update
    if @user.update_attributes(params[:user].permit(:role_ids, :designations_attributes))
      redirect_to user_path(@user), notice: "User updated."
    else
      redirect_to user_path(@user), alert: "Unable to update user"
    end
  end

  # This method is useful to get the list of users related to the hospital when
  # forming a team
  def index
    @hospital = Hospital.find(params[:hospital_id])
    @users = @hospital.users.where(category: "hospital_staff").order(:name)
    respond_with @users do |format|
      format.json
    end
  end

  private

  def find_user
    if signed_in?
      @user = current_user.decorate
    else
      flash[:alert] = "You must sign in first!"
      redirect_to new_user_session_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<section role="user">
  <div class="col-md-8 col-md-offset-1">
    <div class="row user">
      <div class="col-xs-3">
        <span>
          <img src="http://lorempixel.com/output/people-q-c-75-75-7.jpg" alt="Betty" class="img-responsive img-rounded" />
        </span>
      </div>
      <div class="col-xs-9">
        <h3><%= @user.name_link %></h3>
        <span class= "subtitle"><%= @user.role_name %></span>
      </div>
    </div>
    <% if @user.category == "hospital_staff" %>
      <p>
        <h5>List of designations</h5>
        <div class="row">
          <div class="col-sm-6 ">
            <%= form_tag make_default_designations_path, method: :put do %>
              <table id="user-designations-table" class="table table-hover" cellspacing="0">
                <thead>
                  <tr>
                    <th></th>
                    <th>Hospital</th>
                    <th>Designation</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @designations.each do |designation| %>
                    <tr>
                      <td><%= designation.make_default_button %></td>
                      <td><%= link_to designation.hospital.name, hospital_path(designation.hospital.id) %></td>
                      <td><%= link_to designation.name.titleize, edit_designation_path(designation) %></td>
                      <td><%= designation.delete_link(@user) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <%= submit_tag "Default", class: "btn btn-xs btn-primary" %> 
            <% end %>
          </div>
        </div>
        <%= link_to "Add a hospital?", new_designation_path, class: "add-more" %>
      </p>
      <p>
        <h5>List of teams</h5>
        <div class="row">
          <div class="col-sm-6">
            <table id="user-teams-table" class="table table-hover">
              <thead>
                <tr>
                  <th>Team (Members)</th>
                  <th></th>
                  <th>Hospital</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @teams.each do |team| %>
                  <tr>
                    <td><%= link_to team.name, team_path(team) %></td>
                    <td><span class="badge"><%= team.members.count %></span></td>
                    <td><%= link_to team.hospital.name, hospital_path(team.hospital) %></td>
                    <td><%= team.delete_link(@user) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
          <%= link_to "Create a team?", new_team_path %>
      </p>
    <% else %>
      <h5>List of hospitals enrolled</h5>
      <div class="row">
        <div class="col-sm-6">
          <%= form_tag make_default_designations_path, method: :put do %>
            <table cellspacing="0" class="table table-hover" id="user-designations-table">
              <thead>
                <tr>
                  <th></th>
                  <th>Hospital</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @designations.each do |designation| %>
                  <tr>
                    <td><%= designation.make_default_button %></td>
                    <td><%= link_to designation.hospital.name, hospital_path(designation.hospital.id) %></td>
                    <td><%= button_to "Edit", edit_designation_path(designation), method: :get, class: "btn btn-xs btn-primary" %></td>
                    <td><%= designation.delete_link(@user) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%= submit_tag "Default", class: "btn btn-xs btn-primary" %>
          <% end %>
        </div>
      </div>
      <%= link_to "Add another hospital?", new_designation_path %>
    <% end %>
  </div>
</section>