config/routes.rb
Ayosi::Application.routes.draw do
  get "memberships/destroy"
  root to: 'home#index'
  devise_for :users, controllers: { registrations: "registrations"}
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"
  resources :patients, only: [:index, :new, :create, :show]
  resources :users
  resources :data
  resources :designations do
    collection do
      put :make_default
    end
  end
  resources :hospitals do
    resources :users, only: :index
  end
  resources :teams
  resources :memberships, only: :destroy do
    member do
      post :requesting
      post :activating
      post :rejecting
      post :deactivating
      post :banning
      post :resigning
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if signed_in?
      @user = current_user.decorate
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="home">
  <div class="col-md-8 col-md-offset-1">
    <% if signed_in? %>
      <div class="row user">
        <div class="col-xs-3">
          <span>
            <img src="http://lorempixel.com/output/people-q-c-75-75-7.jpg" alt="Betty" class="img-responsive img-rounded" />
          </span>
        </div>
        <div class="col-xs-9">
          <h3><%= @user.name_link %></h3>
          <span class="subtitle"><%= @user.role_name %></span>
        </div>
      </div>
    <% else %>
      <h3>Welcome Visitor!</h3>
    <% end %>
    <div class="row">
      <div class="col-sm-6">
        <p>
          <% if signed_in? %>
            <% if @user.category == "hospital_staff"%>
              <% if @user.roles.count == 0 %>
                Before you proceed, let us know what you do at the hospital
                <%= simple_form_for @user, url: user_path(@user), html: { method: :put}  do |f| %>
                  <%= f.input :role_ids, label: "Role", collection: Role.hospital_staff, as: :radio_buttons, label_method: lambda { |r| r.name.titleize unless r.nil? } %>
                  <%= f.submit "Submit", class: "btn btn-sm btn-primary" %>
                <% end %>
              <% elsif @user.roles.first.name == "doctor" %>
                <p>You need to complete the following:</p>
                <ul class="tasks">
                  <% if @user.hospitals.empty? %>
                    <li><%= link_to "Task 1 - Fill in the hospital details", new_designation_path %></li>
                  <% else %>
                    <li class="strike"><%= link_to "Task 1 - Fill in the hospital details", edit_designation_path(@user.designations.first.id) %><i class="fi-checkbox green"></i></li>
                  <% end %>
                  <% if @user.teams.empty? %>
                    <li>
                      <%= link_to "Task 2 - Set up your team", new_team_path %><br />
                      <span>(Not interested? <%= link_to "Skip!", new_patient_path %>)</span>
                    </li>
                  <% else %>
                      <li class="strike"><%= link_to "Task 2 - Set up your team", edit_team_path(@user.teams.first.id) %><i class="fi-checkbox green"></i></li>
                  <% end %>
                </ul>
              <% else @user.roles.first.name || "doctor" %>
                <p>Something for those who are not doctors</p>
              <% end %>
            <% elsif @user.category == "guest" %>
              A patient? <%= link_to "Edit your account", edit_user_registration_path(@user) %>
            <% else %>
              <%= link_to "Fill in hospital name", new_designation_path %>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</section>