config/routes.rb
Ayosi::Application.routes.draw do
  get "memberships/destroy"
  root to: 'home#index'
  devise_for :users, controllers: { registrations: "registrations"}
  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"
  resources :patients, only: [:index, :new, :create, :show]
  resources :users
  resources :data
  resources :designations do
    collection do
      put :make_default
    end
  end
  resources :hospitals do
    resources :users, only: :index
  end
  resources :teams
  resources :memberships, only: :destroy do
    member do
      post :requesting
      post :activating
      post :rejecting
      post :deactivating
      post :banning
      post :resigning
    end
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  include PgSearch

  # Surgery is the join table for patients and hospitals
  has_many :surgeries
  has_many :hospitals, -> {distinct}, through: :surgeries

  # Client is the join table for patients and users
  has_many :clients
  has_many :users, -> {distinct}, through: :clients

  validates :name, presence: true,
                   uniqueness: { scope: [:age, :gender] }
  validates :age, :gender, presence: true


  accepts_nested_attributes_for :surgeries
  accepts_nested_attributes_for :clients

  # Birthday gem to get the age and other methods
  acts_as_birthday :birthday

  pg_search_scope :search, against: :name, using: {tsearch: {prefix: true, dictionary: "english"} }

  def self.text_search(query)
    if query.present?
      search(query)
    else
      all
    end
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :find_user

  def index
    @patients = @user.patients.text_search(params[:query])
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = PatientForm.new(@user.patients.build)
  end

  def create
    @patient = PatientForm.new(@user.patients.create(patient_params))
    if @patient.save
      flash[:notice] = "Patient #{@patient.name} added to the database"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Patient was not saved due to errors!"
      render action: :new
    end
  end

  private

  def find_user
    if signed_in?
      @user = current_user.decorate
      @hospital = @user.default_hospital
    else
      flash[:alert] = "You must sign in first!"
      redirect_to new_user_session_path
    end
  end

  def patient_params
    params.require(:patient).permit(:id, :name, :age, :birthday, :gender)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= simple_form_for @form do |f| %>
  <%= f.input :name, placeholder: Faker::Name.name, input_html: { title: "Enter the patient's name", data: { tooltip: true } } %>
  <div class="row">
    <div class="col-sm-6">
      <%= f.input :birthday, as: :string, label: "Date of Birth(optional)", input_html: { class: "datepicker"} %>
    </div>
    <div class="col-sm-6">
      <%= f.input :age , placeholder: %w[30 35 40 45 50 55 60 65].sample, collection: (12..110) %>
    </div>
  </div>
  <div class="row">
  </div>
  <%= f.input :gender, as: :radio_buttons, collection: ["Male", "Female", "Others"], item_wrapper_class: 'radio-inline' %>
  <div class="row">
    <div class="col-sm-6">
      <%= f.input :hospital_id, collection: @user.hospitals %>
    </div>
    <div class="col-sm-6">
      <%= f.input :uhid, label: "UHID", placeholder: %w[266900 266153 113203 267443 267623].sample %>
    </div>
  </div>
  <%= f.input :patient_id, as: "hidden" %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :category, collection: ["Primary", "Revision"] %>
    </div>
    <div class="col-md-6">
      <%= f.input :region, collection: ["Hip", "Knee", "Shoulder", "Ankle"] %>
    </div>
  </div>
  <%= f.input :name, placeholder: "Total Hip Replacement", label: "Surgery" %>
  <%= f.input :diagnosis, placeholder: "Primary Osteoarthritis" %>
  <div class="row">
    <div class="col-sm-6">
      <%= f.input :side, as: :radio_buttons, collection: ["Right", "Left"], item_wrapper_class: 'radio-inline' %>
    </div>
    <div class="col-sm-6">
      <%= f.input :date, as: :string, label: "Date of surgery", input_html: { class: "datepicker" }  %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <%= f.input :surgeon, collection: User.doctors %>
    </div>
  </div>
  <%= f.submit "Next", class: "btn btn-primary" %>
<% end %>

app/views/patients/index.html.erb
<section role="patients">
  <div class="col-md-8 col-md-offset-1">
    <h3><%= link_to @hospital.name, hospital_path(@hospital) %></h3>
    <span class="subtitle"><%= @hospital.city %></span>
    <div class="row">
      <div class="col-sm-6">
        <%= form_tag patients_path, method: :get, class: "form-inline" do %>
          <div class="form-group">
            <%= search_field_tag :query, params[:query], size: 40, class: "form-control", placeholder: "Type 3 letters" %>
            <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
    <p>
      <h5>List of patients</h5>
      <div class="row">
        <div class="col-sm-6">
          <table cellspacing="0" class="table table-hover" id="user-hospital-patients">
            <thead>
              <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
              </tr>
            </thead>
              <% @patients.each do |patient| %>
                <tr>
                  <td><%= link_to patient.name, patient_path(patient) %></td>
                  <td><%= patient.age %></td>
                  <td><%= patient.gender %></td>
                </tr>
              <% end %>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </p>
  </div>
</section>

app/views/patients/new.html.erb
<hgroup class="col-md-6 col-md-offset-1">
  <div class="row">
    <h2 class="col-lg-6 pull-left">Step 1</h2>
    <sgroup class="col-lg-6 pull-right">
      <% unless @hospital.nil? %>
        <span class="pull-right"><%= link_to @hospital.name, user_path(@user) %></span><br />
        <span class="pull-right"><%= link_to @hospital.city, user_path(@user) %></span>
      <% else %>
        <%= link_to "Add hospital", new_designation_path %>
      <% end %>
    </sgroup>
  </div>
</hgroup>
<div class="col-md-6 col-md-offset-1">
  <%= render 'form' %>
</div>

app/views/patients/show.html.erb
<section role="patient">
  <div class="col-md-8 col-md-offset-1">
    <div class="row patient">
      <div class="col-xs-3">
        <span>
          <img src="http://lorempixel.com/output/people-q-c-75-75-7.jpg" alt="Betty" class="img-responsive img-rounded" />
        </span>
      </div>
      <div class="col-xs-9">
        <h3><%= @patient.name %></h3>
        <span class="subtitle"><%= @patient.age %> / <%= @patient.gender %></span>
      </div>
    </div>
  </div>
</section>